### ISSUE TITLE
Platform minimum requirement documented as ios 7.0+, but required ios 8.0 from podspec file

### ISSUE THREAD

**Issue by matteogirardi** [nghialv/Transporter#4]
While into file TransporterSwift.podspec there's a deployment target valued to "8.0", on README.md is stated the library is compatible with ios 7.0+
I this you should update README.md file to match requirements stated within podspec.

**Comment by nghialv** [comment]
Hi @matteogirardi . Thanks for your reporting. I have just updated the Readme file.
